/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.listas;

import javax.swing.ImageIcon;

/**
 *
 * @author Usuario iTC
 */
public class FrmRegistroDocenteGeneral extends javax.swing.JFrame {

    
    
    public FrmRegistroDocenteGeneral() {
        initComponents();
        panelLogo.setIcon(new ImageIcon("multimedia/LogoUNL.jpg"));
        panelDocente.setIcon(new ImageIcon("multimedia/LogoRegistro.jpg"));
        panelEspecializacion.setIcon(new ImageIcon("multimedia/LogoEspecializacion.jpg"));
        panelTitulo.setIcon(new ImageIcon("multimedia/LogoTitulo.png"));
        panelCertificado.setIcon(new ImageIcon("multimedia/LogoCertificado.jpg"));
        this.setLocationRelativeTo(null);
        limpiar();
    }
    
    private void limpiar(){
       
    }
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        panel2 = new org.edisoncor.gui.panel.Panel();
        labelRound1 = new org.edisoncor.gui.label.LabelRound();
        panelLogo = new org.edisoncor.gui.panel.PanelImage();
        btnCertificado = new org.edisoncor.gui.button.ButtonAqua();
        btnTitulo = new org.edisoncor.gui.button.ButtonAqua();
        panel3 = new org.edisoncor.gui.panel.Panel();
        panel4 = new org.edisoncor.gui.panel.Panel();
        labelRound2 = new org.edisoncor.gui.label.LabelRound();
        panelLogo1 = new org.edisoncor.gui.panel.PanelImage();
        btnDocente = new org.edisoncor.gui.button.ButtonAqua();
        btnEspecializacion = new org.edisoncor.gui.button.ButtonAqua();
        panelEspecializacion = new org.edisoncor.gui.panel.PanelImage();
        panelDocente = new org.edisoncor.gui.panel.PanelImage();
        panelCertificado = new org.edisoncor.gui.panel.PanelImage();
        panelTitulo = new org.edisoncor.gui.panel.PanelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setColorPrimario(new java.awt.Color(255, 255, 255));
        panel1.setColorSecundario(new java.awt.Color(255, 255, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel2.setColorPrimario(new java.awt.Color(0, 102, 153));
        panel2.setColorSecundario(new java.awt.Color(0, 102, 153));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelRound1.setBackground(new java.awt.Color(0, 102, 153));
        labelRound1.setText("Registro de Docente");
        labelRound1.setColorDeBorde(new java.awt.Color(0, 102, 153));
        labelRound1.setColorDeSegundoBorde(new java.awt.Color(0, 102, 153));
        labelRound1.setColorDeSombra(new java.awt.Color(0, 102, 153));
        labelRound1.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        panel2.add(labelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 650, 90));

        panelLogo.setBackground(new java.awt.Color(0, 102, 153));
        panelLogo.setForeground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout panelLogoLayout = new javax.swing.GroupLayout(panelLogo);
        panelLogo.setLayout(panelLogoLayout);
        panelLogoLayout.setHorizontalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        panelLogoLayout.setVerticalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        panel2.add(panelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 90));

        panel1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 90));

        btnCertificado.setText("CERTIFICADO");
        btnCertificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCertificadoActionPerformed(evt);
            }
        });
        panel1.add(btnCertificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 540, -1, -1));

        btnTitulo.setText("TITULO PROFESIONAL");
        btnTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTituloActionPerformed(evt);
            }
        });
        panel1.add(btnTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, -1, -1));

        panel3.setColorPrimario(new java.awt.Color(255, 255, 255));
        panel3.setColorSecundario(new java.awt.Color(255, 255, 255));
        panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel4.setColorPrimario(new java.awt.Color(0, 102, 153));
        panel4.setColorSecundario(new java.awt.Color(0, 102, 153));
        panel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelRound2.setBackground(new java.awt.Color(0, 102, 153));
        labelRound2.setText("Registro de Docente");
        labelRound2.setColorDeBorde(new java.awt.Color(0, 102, 153));
        labelRound2.setColorDeSegundoBorde(new java.awt.Color(0, 102, 153));
        labelRound2.setColorDeSombra(new java.awt.Color(0, 102, 153));
        labelRound2.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        panel4.add(labelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 650, 90));

        panelLogo1.setBackground(new java.awt.Color(0, 102, 153));
        panelLogo1.setForeground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout panelLogo1Layout = new javax.swing.GroupLayout(panelLogo1);
        panelLogo1.setLayout(panelLogo1Layout);
        panelLogo1Layout.setHorizontalGroup(
            panelLogo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        panelLogo1Layout.setVerticalGroup(
            panelLogo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        panel4.add(panelLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 90));

        panel3.add(panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 90));

        panel1.add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnDocente.setBackground(new java.awt.Color(51, 51, 255));
        btnDocente.setText("DOCENTE");
        btnDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocenteActionPerformed(evt);
            }
        });
        panel1.add(btnDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        btnEspecializacion.setText("ESPECIALIZACIÓN");
        btnEspecializacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspecializacionActionPerformed(evt);
            }
        });
        panel1.add(btnEspecializacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, -1));

        javax.swing.GroupLayout panelEspecializacionLayout = new javax.swing.GroupLayout(panelEspecializacion);
        panelEspecializacion.setLayout(panelEspecializacionLayout);
        panelEspecializacionLayout.setHorizontalGroup(
            panelEspecializacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        panelEspecializacionLayout.setVerticalGroup(
            panelEspecializacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        panel1.add(panelEspecializacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 120, 120));

        javax.swing.GroupLayout panelDocenteLayout = new javax.swing.GroupLayout(panelDocente);
        panelDocente.setLayout(panelDocenteLayout);
        panelDocenteLayout.setHorizontalGroup(
            panelDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        panelDocenteLayout.setVerticalGroup(
            panelDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        panel1.add(panelDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 120, 120));

        javax.swing.GroupLayout panelCertificadoLayout = new javax.swing.GroupLayout(panelCertificado);
        panelCertificado.setLayout(panelCertificadoLayout);
        panelCertificadoLayout.setHorizontalGroup(
            panelCertificadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        panelCertificadoLayout.setVerticalGroup(
            panelCertificadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        panel1.add(panelCertificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, -1, -1));

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        panel1.add(panelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocenteActionPerformed
       
    }//GEN-LAST:event_btnDocenteActionPerformed

    private void btnEspecializacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspecializacionActionPerformed
       
    }//GEN-LAST:event_btnEspecializacionActionPerformed

    private void btnTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTituloActionPerformed
        
    }//GEN-LAST:event_btnTituloActionPerformed

    private void btnCertificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCertificadoActionPerformed
        
    }//GEN-LAST:event_btnCertificadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroDocenteGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroDocenteGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroDocenteGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroDocenteGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistroDocenteGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonAqua btnCertificado;
    private org.edisoncor.gui.button.ButtonAqua btnDocente;
    private org.edisoncor.gui.button.ButtonAqua btnEspecializacion;
    private org.edisoncor.gui.button.ButtonAqua btnTitulo;
    private org.edisoncor.gui.label.LabelRound labelRound1;
    private org.edisoncor.gui.label.LabelRound labelRound2;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.Panel panel2;
    private org.edisoncor.gui.panel.Panel panel3;
    private org.edisoncor.gui.panel.Panel panel4;
    private org.edisoncor.gui.panel.PanelImage panelCertificado;
    private org.edisoncor.gui.panel.PanelImage panelDocente;
    private org.edisoncor.gui.panel.PanelImage panelEspecializacion;
    private org.edisoncor.gui.panel.PanelImage panelLogo;
    private org.edisoncor.gui.panel.PanelImage panelLogo1;
    private org.edisoncor.gui.panel.PanelImage panelTitulo;
    // End of variables declaration//GEN-END:variables
}
