/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.listas;

import controlador.TDA.listas.LinkedList;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Administrador;
import modelo.Cuenta;
import modelo.Docente;
import modelo.Estudiante;
import modelo.controladores.AdministradorController;
import modelo.controladores.CuentaController;
import modelo.controladores.DocenteController;
import modelo.controladores.EstudianteController;

/**
 *
 * @author Usuario iTC
 */
public class FrmVistaGeneral extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmVistaGeneral() {
        initComponents();
        this.setLocationRelativeTo(null);
        

    }
    EstudianteController estudianteControlador = new EstudianteController();
    DocenteController docenteControlador = new DocenteController();
    AdministradorController administradorController = new AdministradorController();
    CuentaController cuentaControlador = new CuentaController();

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        panel4 = new org.edisoncor.gui.panel.Panel();
        panel3 = new org.edisoncor.gui.panel.Panel();
        panelCurves2 = new org.edisoncor.gui.panel.PanelCurves();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        userLabel = new javax.swing.JLabel();
        buttonAction2 = new org.edisoncor.gui.button.ButtonAction();
        labelRect1 = new org.edisoncor.gui.label.LabelRect();
        labelRect2 = new org.edisoncor.gui.label.LabelRect();
        labelRect3 = new org.edisoncor.gui.label.LabelRect();
        labelRect4 = new org.edisoncor.gui.label.LabelRect();
        labelRect5 = new org.edisoncor.gui.label.LabelRect();
        labelRect6 = new org.edisoncor.gui.label.LabelRect();
        labelRect7 = new org.edisoncor.gui.label.LabelRect();
        labelRect8 = new org.edisoncor.gui.label.LabelRect();
        labelRect9 = new org.edisoncor.gui.label.LabelRect();
        labelRect10 = new org.edisoncor.gui.label.LabelRect();
        labelRect11 = new org.edisoncor.gui.label.LabelRect();
        labelRect12 = new org.edisoncor.gui.label.LabelRect();
        labelRect13 = new org.edisoncor.gui.label.LabelRect();
        buttonAction3 = new org.edisoncor.gui.button.ButtonAction();
        buttonAction4 = new org.edisoncor.gui.button.ButtonAction();
        buttonAction5 = new org.edisoncor.gui.button.ButtonAction();
        buttonAction6 = new org.edisoncor.gui.button.ButtonAction();
        buttonAction7 = new org.edisoncor.gui.button.ButtonAction();
        buttonAction8 = new org.edisoncor.gui.button.ButtonAction();
        buttonAction9 = new org.edisoncor.gui.button.ButtonAction();
        buttonAction10 = new org.edisoncor.gui.button.ButtonAction();
        buttonAction11 = new org.edisoncor.gui.button.ButtonAction();
        buttonAction12 = new org.edisoncor.gui.button.ButtonAction();
        buttonAction13 = new org.edisoncor.gui.button.ButtonAction();
        buttonAction14 = new org.edisoncor.gui.button.ButtonAction();
        buttonAction15 = new org.edisoncor.gui.button.ButtonAction();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setColorPrimario(new java.awt.Color(255, 255, 255));
        panel1.setColorSecundario(new java.awt.Color(255, 255, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panel1.add(panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 890, 10));

        panel3.setColorPrimario(new java.awt.Color(0, 102, 153));
        panel3.setColorSecundario(new java.awt.Color(0, 102, 153));
        panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCurves1.setBackground(new java.awt.Color(153, 204, 255));
        panelCurves1.setForeground(new java.awt.Color(153, 204, 255));
        panelCurves2.add(panelCurves1, java.awt.BorderLayout.LINE_START);

        userLabel.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        userLabel.setForeground(new java.awt.Color(0, 0, 0));
        userLabel.setText("Herramientas Administrador");
        panelCurves2.add(userLabel, java.awt.BorderLayout.LINE_END);

        panel3.add(panelCurves2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 60));

        panel1.add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 60));

        buttonAction2.setText("Ir");
        buttonAction2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction2ActionPerformed(evt);
            }
        });
        panel1.add(buttonAction2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, -1, -1));

        labelRect1.setText("Registrar Logro E.");
        labelRect1.setColorDeBorde(new java.awt.Color(0, 0, 0));
        labelRect1.setColorDeSegundoBorde(new java.awt.Color(0, 0, 0));
        panel1.add(labelRect1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 150, 30));

        labelRect2.setText("Registrar Ciclo");
        labelRect2.setColorDeBorde(new java.awt.Color(51, 51, 51));
        labelRect2.setColorDeSegundoBorde(new java.awt.Color(51, 51, 51));
        panel1.add(labelRect2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 150, 30));

        labelRect3.setText("Registrar Curso");
        labelRect3.setColorDeBorde(new java.awt.Color(0, 0, 0));
        labelRect3.setColorDeSegundoBorde(new java.awt.Color(0, 0, 0));
        panel1.add(labelRect3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 150, 30));

        labelRect4.setText("Registrar Docente");
        labelRect4.setColorDeBorde(new java.awt.Color(0, 0, 0));
        labelRect4.setColorDeSegundoBorde(new java.awt.Color(0, 0, 0));
        panel1.add(labelRect4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 150, 30));

        labelRect5.setText("Registrar Estudiante");
        labelRect5.setColorDeBorde(new java.awt.Color(0, 0, 0));
        labelRect5.setColorDeSegundoBorde(new java.awt.Color(0, 0, 0));
        panel1.add(labelRect5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 150, 30));

        labelRect6.setText("Registrar Genero");
        labelRect6.setColorDeBorde(new java.awt.Color(0, 0, 0));
        labelRect6.setColorDeSegundoBorde(new java.awt.Color(0, 0, 0));
        panel1.add(labelRect6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 150, 30));

        labelRect7.setText("Registrar Malla");
        labelRect7.setColorDeBorde(new java.awt.Color(0, 0, 0));
        labelRect7.setColorDeSegundoBorde(new java.awt.Color(0, 0, 0));
        panel1.add(labelRect7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 150, 30));

        labelRect8.setText("Registrar Materia");
        labelRect8.setColorDeBorde(new java.awt.Color(0, 0, 0));
        labelRect8.setColorDeSegundoBorde(new java.awt.Color(0, 0, 0));
        panel1.add(labelRect8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 150, 30));

        labelRect9.setText("Registrar Matricula");
        labelRect9.setColorDeBorde(new java.awt.Color(0, 0, 0));
        labelRect9.setColorDeSegundoBorde(new java.awt.Color(0, 0, 0));
        panel1.add(labelRect9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 150, 30));

        labelRect10.setText("Registrar Paralelo");
        labelRect10.setColorDeBorde(new java.awt.Color(0, 0, 0));
        labelRect10.setColorDeSegundoBorde(new java.awt.Color(0, 0, 0));
        panel1.add(labelRect10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 150, 30));

        labelRect11.setText("Registrar Periodo A.");
        labelRect11.setColorDeBorde(new java.awt.Color(0, 0, 0));
        labelRect11.setColorDeSegundoBorde(new java.awt.Color(0, 0, 0));
        panel1.add(labelRect11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 150, 30));

        labelRect12.setText("Registrar Rol");
        labelRect12.setColorDeBorde(new java.awt.Color(0, 0, 0));
        labelRect12.setColorDeSegundoBorde(new java.awt.Color(0, 0, 0));
        panel1.add(labelRect12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 150, 30));

        labelRect13.setText("Registrar TipoLogro");
        labelRect13.setColorDeBorde(new java.awt.Color(0, 0, 0));
        labelRect13.setColorDeSegundoBorde(new java.awt.Color(0, 0, 0));
        panel1.add(labelRect13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 150, 30));

        buttonAction3.setText("Ir");
        buttonAction3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction3ActionPerformed(evt);
            }
        });
        panel1.add(buttonAction3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        buttonAction4.setText("Ir");
        buttonAction4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction4ActionPerformed(evt);
            }
        });
        panel1.add(buttonAction4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        buttonAction5.setText("Ir");
        buttonAction5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction5ActionPerformed(evt);
            }
        });
        panel1.add(buttonAction5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        buttonAction6.setText("Ir");
        panel1.add(buttonAction6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        buttonAction7.setText("Ir");
        buttonAction7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction7ActionPerformed(evt);
            }
        });
        panel1.add(buttonAction7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        buttonAction8.setText("Ir");
        buttonAction8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction8ActionPerformed(evt);
            }
        });
        panel1.add(buttonAction8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        buttonAction9.setText("Ir");
        buttonAction9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction9ActionPerformed(evt);
            }
        });
        panel1.add(buttonAction9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        buttonAction10.setText("Ir");
        buttonAction10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction10ActionPerformed(evt);
            }
        });
        panel1.add(buttonAction10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        buttonAction11.setText("Ir");
        buttonAction11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction11ActionPerformed(evt);
            }
        });
        panel1.add(buttonAction11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));

        buttonAction12.setText("Ir");
        buttonAction12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction12ActionPerformed(evt);
            }
        });
        panel1.add(buttonAction12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, -1, -1));

        buttonAction13.setText("Ir");
        buttonAction13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction13ActionPerformed(evt);
            }
        });
        panel1.add(buttonAction13, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, -1, -1));

        buttonAction14.setText("Ir");
        buttonAction14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction14ActionPerformed(evt);
            }
        });
        panel1.add(buttonAction14, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, -1, -1));

        buttonAction15.setText("Ir");
        buttonAction15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction15ActionPerformed(evt);
            }
        });
        panel1.add(buttonAction15, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAction3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction3ActionPerformed
        new FrmCiclo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAction3ActionPerformed

    private void buttonAction4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction4ActionPerformed
        new FrmCurso().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAction4ActionPerformed

    private void buttonAction5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction5ActionPerformed
        new FrmDocente().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAction5ActionPerformed

    private void buttonAction7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction7ActionPerformed
        new FrmEstudiante().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAction7ActionPerformed

    private void buttonAction8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction8ActionPerformed
        new FrmGenero().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAction8ActionPerformed

    private void buttonAction9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction9ActionPerformed
        new FrmMalla().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAction9ActionPerformed

    private void buttonAction10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction10ActionPerformed
        new FrmMateria().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAction10ActionPerformed

    private void buttonAction11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction11ActionPerformed
        new FrmMatricula().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAction11ActionPerformed

    private void buttonAction12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction12ActionPerformed
        new FrmParalelo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAction12ActionPerformed

    private void buttonAction13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction13ActionPerformed
        new FrmPeriodoAcademico().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAction13ActionPerformed

    private void buttonAction14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction14ActionPerformed
        new FrmRol().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAction14ActionPerformed

    private void buttonAction15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction15ActionPerformed
        new FrmTipoLogro().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAction15ActionPerformed

    private void buttonAction2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction2ActionPerformed
        new FrmLogroEducativo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAction2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVistaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVistaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVistaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVistaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVistaGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonAction buttonAction10;
    private org.edisoncor.gui.button.ButtonAction buttonAction11;
    private org.edisoncor.gui.button.ButtonAction buttonAction12;
    private org.edisoncor.gui.button.ButtonAction buttonAction13;
    private org.edisoncor.gui.button.ButtonAction buttonAction14;
    private org.edisoncor.gui.button.ButtonAction buttonAction15;
    private org.edisoncor.gui.button.ButtonAction buttonAction2;
    private org.edisoncor.gui.button.ButtonAction buttonAction3;
    private org.edisoncor.gui.button.ButtonAction buttonAction4;
    private org.edisoncor.gui.button.ButtonAction buttonAction5;
    private org.edisoncor.gui.button.ButtonAction buttonAction6;
    private org.edisoncor.gui.button.ButtonAction buttonAction7;
    private org.edisoncor.gui.button.ButtonAction buttonAction8;
    private org.edisoncor.gui.button.ButtonAction buttonAction9;
    private org.edisoncor.gui.label.LabelRect labelRect1;
    private org.edisoncor.gui.label.LabelRect labelRect10;
    private org.edisoncor.gui.label.LabelRect labelRect11;
    private org.edisoncor.gui.label.LabelRect labelRect12;
    private org.edisoncor.gui.label.LabelRect labelRect13;
    private org.edisoncor.gui.label.LabelRect labelRect2;
    private org.edisoncor.gui.label.LabelRect labelRect3;
    private org.edisoncor.gui.label.LabelRect labelRect4;
    private org.edisoncor.gui.label.LabelRect labelRect5;
    private org.edisoncor.gui.label.LabelRect labelRect6;
    private org.edisoncor.gui.label.LabelRect labelRect7;
    private org.edisoncor.gui.label.LabelRect labelRect8;
    private org.edisoncor.gui.label.LabelRect labelRect9;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.Panel panel3;
    private org.edisoncor.gui.panel.Panel panel4;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.panel.PanelCurves panelCurves2;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
